### ISSUE TITLE
UMLight Identification

### ISSUE THREAD

**Issue by Raphael-Lemaire** [ValentinCharbonneau/Beta-UMLight#3]
Bonjour,

Lors de l'identification sur l'application UMLight, il est demandé d'entrer l'identifiant du profil mais si l'on rentre le prénom ou le nom du profil cela ne marche pas il faut obligatoirement l'email, il faudrait préciser qu'on attend l'email lors de l'identification.

**Comment by ValentinCharbonneau** [comment]
Bonjour,

J'ai remplacé "Identifiant" par "Email" dans le dernier commit.
Vous pouvez utiliser l'installer (UMLight-Installer.exe) pour réinstaller UMLight et ainsi le mettre à jour. Cela n’effacera pas votre base de données.

Cordialement,
Valentin CHARBONNEAU
