### ISSUE TITLE
Problème de suppression de table SQL

### ISSUE THREAD

**Issue by KilianDunat** [ValentinCharbonneau/Beta-UMLight#6]
Bonjour,

Lorsque je clique pour recréer la base de données sous PostgreSQL cela garde les anciens enregistrement alors que cela devrait être supprimer. 

En espérant que ce problème soit résolut au plus vite.

Cordialement.

**Comment by ValentinCharbonneau** [comment]
Bonjour,

Ce problème était dû à une requête SQL interne au logiciel qui s'est avérée non fonctionnelle pour PostgreSQL, même si non bloquante pour l'application.
Le problème est résolu dans le dernier commit, vous pouvez utiliser l'installer dont vous disposez déjà pour mettre UMLight et UMLight-Admin à jour en les réinstallant.

Cordialement.
